export const TOKEN_REGISTER_REQUEST = "TOKEN_REGISTER_REQUEST";
export const TOKEN_REGISTER_SUCCESS = "TOKEN_REGISTER_SUCCESS";
export const TOKEN_REGISTER_FAIL = "TOKEN_REGISTER_FAIL";

export const TOKEN_DETAILS_REQUEST = "TOKEN_DETAILS_REQUEST";
export const TOKEN_DETAILS_SUCCESS = "TOKEN_DETAILS_SUCCESS";
export const TOKEN_DETAILS_FAIL = "TOKEN_DETAILS_FAIL";

export const TOKEN_UPDATE_REQUEST = "TOKEN_UPDATE_REQUEST";
export const TOKEN_UPDATE_SUCCESS = "TOKEN_UPDATE_SUCCESS";
export const TOKEN_UPDATE_FAIL = "TOKEN_UPDATE_FAIL";
export const TOKEN_UPDATE_RESET = "TOKEN_UPDATE_RESET";

export const TOKEN_LIST_REQUEST = "TOKEN_LIST_REQUEST";
export const TOKEN_LIST_SUCCESS = "TOKEN_LIST_SUCCESS";
export const TOKEN_LIST_FAIL = "TOKEN_LIST_FAIL";

export const TOKEN_BOOKMARK_REQUEST = "TOKEN_BOOKMARK_REQUEST";
export const TOKEN_BOOKMARK_SUCCESS = "TOKEN_BOOKMARK_SUCCESS";
export const TOKEN_BOOKMARK_FAIL = "TOKEN_BOOKMARK_FAIL";

export const TOKEN_UPVOTE_REQUEST = "TOKEN_UPVOTE_REQUEST";
export const TOKEN_UPVOTE_SUCCESS = "TOKEN_UPVOTE_SUCCESS";
export const TOKEN_UPVOTE_FAIL = "TOKEN_UPVOTE_FAIL";

export const TOKEN_REVIEW_REQUEST = "TOKEN_REVIEW_REQUEST";
export const TOKEN_REVIEW_SUCCESS = "TOKEN_REVIEW_SUCCESS";
export const TOKEN_REVIEW_FAIL = "TOKEN_REVIEW_FAIL";
export const TOKEN_REVIEW_RESET= "TOKEN_REVIEW_RESET"

export const UPVOTED_TOKEN_REQUEST = "UPVOTED_TOKEN_REQUEST";
export const UPVOTED_TOKEN_SUCCESS = "UPVOTED_TOKEN_SUCCESS";
export const UPVOTED_TOKEN_FAIL = "UPVOTED_TOKEN_FAIL";

export const BOOKMARKED_TOKEN_REQUEST = "BOOKMARKED_TOKEN_REQUEST";
export const BOOKMARKED_TOKEN_SUCCESS = "BOOKMARKED_TOKEN_SUCCESS";
export const BOOKMARKED_TOKEN_FAIL = "BOOKMARKED_TOKEN_FAIL";